version: 0.2

phases:
build:
  commands:
    - echo Building...
artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    artifact1:
      files:
        base-directory: 'fileupload_download/target/Myproject'
        name: Myproject
    artifact2:
      files:
        base-directory: 'insurance_agent/target/Myproject2'
        name: Myproject2
    artifact3:
      files:
        base-directory: 'springwebex/target/Myproject3'
        name: Myproject3
